Switch to using find_package(gRPC). Still the same linking issue:
[ 77%] Built target mainInterface
[ 77%] Built target geosx_core
[ 77%] Linking CXX executable bin/geosx
lib/libgeosx_core.so: undefined reference to `grpc::InsecureChannelCredentials()'
lib/libgeosx_core.so: undefined reference to `grpc::CreateChannel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<grpc::ChannelCredentials> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/geosx.dir/build.make:217: bin/geosx] Error 1
make[1]: *** [CMakeFiles/Makefile2:1475: CMakeFiles/geosx.dir/all] Error 2
make: *** [Makefile:146: all] Error 2